spring:
  application:
    name: telegram_bot
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: root
    password: 14031988
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect